import type { Member } from '@/types'

export const members: Member[] = [
    {
        id: 'm001',
        name: 'Mia Torres',
        email: 'mia.torres@example.com',
        phone: '+1 408-855-7890',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia',
        plan: 'Premium',
        status: 'Active',
        trainer: 'Chris Evans',
        joinDate: '2024-02-18',
        dateOfBirth: '1993-03-28',
        gender: 'Female',
        address: 'Jl. Melati No. 45, Sleman, Yogyakarta, Indonesia',
        attendanceRate: 87,
        emergencyContact: 'Juan Torres +1 408-555-1234',
    },
    {
        id: 'm002',
        name: 'Jake Ramirez',
        email: 'jake.ramirez@example.com',
        phone: '+1 512-334-2211',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jake',
        plan: 'Standard',
        status: 'Active',
        trainer: 'Sarah Lee',
        joinDate: '2024-05-10',
        dateOfBirth: '1990-07-14',
        gender: 'Male',
        address: '23 Maple Ave, Austin, TX',
        attendanceRate: 72,
        emergencyContact: 'Maria Ramirez +1 512-555-9876',
    },
    {
        id: 'm003',
        name: 'Priya Sharma',
        email: 'priya.sharma@example.com',
        phone: '+91 98765 43210',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
        plan: 'Premium',
        status: 'Active',
        trainer: 'Chris Evans',
        joinDate: '2023-11-01',
        dateOfBirth: '1995-09-22',
        gender: 'Female',
        address: '7 Park Street, Mumbai, India',
        attendanceRate: 94,
        emergencyContact: 'Raj Sharma +91 98700 11223',
    },
    {
        id: 'm004',
        name: 'Oliver Ng',
        email: 'oliver.ng@example.com',
        phone: '+65 9123 4567',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver',
        plan: 'Basic',
        status: 'Inactive',
        trainer: 'Mike Johnson',
        joinDate: '2024-01-20',
        dateOfBirth: '1988-04-03',
        gender: 'Male',
        address: '88 Orchard Rd, Singapore',
        attendanceRate: 45,
        emergencyContact: 'Lily Ng +65 9000 1122',
    },
    {
        id: 'm005',
        name: 'Amara Diallo',
        email: 'amara.diallo@example.com',
        phone: '+33 6 12 34 56 78',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amara',
        plan: 'Standard',
        status: 'Active',
        trainer: 'Sarah Lee',
        joinDate: '2024-03-15',
        dateOfBirth: '1997-12-10',
        gender: 'Female',
        address: '14 Rue de Paris, Lyon, France',
        attendanceRate: 81,
        emergencyContact: 'Fatou Diallo +33 6 99 88 77 66',
    },
    {
        id: 'm006',
        name: 'Ethan Brooks',
        email: 'ethan.brooks@example.com',
        phone: '+1 646-555-0192',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan',
        plan: 'Premium',
        status: 'Active',
        trainer: 'Mike Johnson',
        joinDate: '2023-09-05',
        dateOfBirth: '1991-01-17',
        gender: 'Male',
        address: '501 W 42nd St, New York, NY',
        attendanceRate: 90,
        emergencyContact: 'Claire Brooks +1 646-555-7788',
    },
    {
        id: 'm007',
        name: 'Sofia Herrera',
        email: 'sofia.herrera@example.com',
        phone: '+52 55 1234 5678',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
        plan: 'Basic',
        status: 'Active',
        trainer: 'Sarah Lee',
        joinDate: '2024-06-01',
        dateOfBirth: '1999-05-30',
        gender: 'Female',
        address: 'Calle Reforma 200, CDMX, Mexico',
        attendanceRate: 63,
        emergencyContact: 'Luis Herrera +52 55 9876 5432',
    },
    {
        id: 'm008',
        name: 'Ryan Kim',
        email: 'ryan.kim@example.com',
        phone: '+82 10 1234 5678',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan',
        plan: 'Standard',
        status: 'Suspended',
        trainer: 'Chris Evans',
        joinDate: '2023-12-10',
        dateOfBirth: '1994-08-21',
        gender: 'Male',
        address: '123 Gangnam-daero, Seoul, Korea',
        attendanceRate: 55,
        emergencyContact: 'Jin Kim +82 10 9999 0000',
    },
    {
        id: 'm009',
        name: 'Lena Mueller',
        email: 'lena.mueller@example.com',
        phone: '+49 170 1234567',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lena',
        plan: 'Premium',
        status: 'Active',
        trainer: 'Mike Johnson',
        joinDate: '2024-01-08',
        dateOfBirth: '1996-11-04',
        gender: 'Female',
        address: 'Hauptstrasse 10, Berlin, Germany',
        attendanceRate: 88,
        emergencyContact: 'Hans Mueller +49 170 9876543',
    },
    {
        id: 'm010',
        name: 'Carlos Vega',
        email: 'carlos.vega@example.com',
        phone: '+34 612 345 678',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
        plan: 'Basic',
        status: 'Active',
        trainer: 'Sarah Lee',
        joinDate: '2024-07-22',
        dateOfBirth: '1985-02-14',
        gender: 'Male',
        address: 'Calle Gran Via 50, Madrid, Spain',
        attendanceRate: 70,
        emergencyContact: 'Ana Vega +34 612 987 654',
    },
    {
        id: 'm011',
        name: 'Yuki Tanaka',
        email: 'yuki.tanaka@example.com',
        phone: '+81 90 1234 5678',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yuki',
        plan: 'Standard',
        status: 'Active',
        trainer: 'Chris Evans',
        joinDate: '2024-04-11',
        dateOfBirth: '1998-07-07',
        gender: 'Female',
        address: '1-2-3 Shibuya, Tokyo, Japan',
        attendanceRate: 83,
        emergencyContact: 'Kenji Tanaka +81 90 8888 7777',
    },
    {
        id: 'm012',
        name: 'Marcus Williams',
        email: 'marcus.williams@example.com',
        phone: '+1 323-555-8899',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
        plan: 'Premium',
        status: 'Active',
        trainer: 'Mike Johnson',
        joinDate: '2023-10-25',
        dateOfBirth: '1989-03-16',
        gender: 'Male',
        address: '3000 Sunset Blvd, Los Angeles, CA',
        attendanceRate: 91,
        emergencyContact: 'Diana Williams +1 323-555-1011',
    },
    {
        id: 'm013',
        name: 'Aisha Patel',
        email: 'aisha.patel@example.com',
        phone: '+44 7911 123456',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
        plan: 'Standard',
        status: 'Active',
        trainer: 'Sarah Lee',
        joinDate: '2024-02-28',
        dateOfBirth: '2000-01-25',
        gender: 'Female',
        address: '42 Baker St, London, UK',
        attendanceRate: 76,
        emergencyContact: 'Raj Patel +44 7922 654321',
    },
    {
        id: 'm014',
        name: 'Tom Nguyen',
        email: 'tom.nguyen@example.com',
        phone: '+84 90 123 4567',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom',
        plan: 'Basic',
        status: 'Inactive',
        trainer: 'Chris Evans',
        joinDate: '2024-08-05',
        dateOfBirth: '1993-06-09',
        gender: 'Male',
        address: '10 Le Loi, Ho Chi Minh City, Vietnam',
        attendanceRate: 38,
        emergencyContact: 'Lan Nguyen +84 90 888 1234',
    },
    {
        id: 'm015',
        name: 'Emma Wilson',
        email: 'emma.wilson@example.com',
        phone: '+1 604-555-0133',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
        plan: 'Premium',
        status: 'Active',
        trainer: 'Mike Johnson',
        joinDate: '2023-08-14',
        dateOfBirth: '1992-10-31',
        gender: 'Female',
        address: '500 Pacific Blvd, Vancouver, BC',
        attendanceRate: 93,
        emergencyContact: 'James Wilson +1 604-555-9977',
    },
    {
        id: 'm016',
        name: 'David Chen',
        email: 'david.chen@example.com',
        phone: '+86 138 1234 5678',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
        plan: 'Standard',
        status: 'Active',
        trainer: 'Sarah Lee',
        joinDate: '2024-09-01',
        dateOfBirth: '1987-12-20',
        gender: 'Male',
        address: '88 Nanjing Road, Shanghai, China',
        attendanceRate: 68,
        emergencyContact: 'Wei Chen +86 138 9999 0001',
    },
    {
        id: 'm017',
        name: 'Fatima Al-Rashid',
        email: 'fatima.alrashid@example.com',
        phone: '+971 50 123 4567',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
        plan: 'Premium',
        status: 'Active',
        trainer: 'Chris Evans',
        joinDate: '2024-03-22',
        dateOfBirth: '1995-04-17',
        gender: 'Female',
        address: 'Sheikh Zayed Rd, Dubai, UAE',
        attendanceRate: 85,
        emergencyContact: 'Omar Al-Rashid +971 50 765 4321',
    },
    {
        id: 'm018',
        name: 'Luis Fernandez',
        email: 'luis.fernandez@example.com',
        phone: '+54 11 4567 8901',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luis',
        plan: 'Basic',
        status: 'Active',
        trainer: 'Mike Johnson',
        joinDate: '2024-10-10',
        dateOfBirth: '2001-09-05',
        gender: 'Male',
        address: 'Av. Corrientes 1234, Buenos Aires, Argentina',
        attendanceRate: 59,
        emergencyContact: 'Rosa Fernandez +54 11 9876 5432',
    },
    {
        id: 'm019',
        name: 'Natasha Ivanova',
        email: 'natasha.ivanova@example.com',
        phone: '+7 916 123 45 67',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natasha',
        plan: 'Standard',
        status: 'Active',
        trainer: 'Sarah Lee',
        joinDate: '2024-01-30',
        dateOfBirth: '1994-02-28',
        gender: 'Female',
        address: 'Tverskaya 10, Moscow, Russia',
        attendanceRate: 79,
        emergencyContact: 'Alexei Ivanov +7 916 987 65 43',
    },
    {
        id: 'm020',
        name: 'James Okafor',
        email: 'james.okafor@example.com',
        phone: '+234 803 123 4567',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
        plan: 'Premium',
        status: 'Suspended',
        trainer: 'Chris Evans',
        joinDate: '2023-07-19',
        dateOfBirth: '1986-11-11',
        gender: 'Male',
        address: '5 Victoria Island, Lagos, Nigeria',
        attendanceRate: 62,
        emergencyContact: 'Grace Okafor +234 803 987 6543',
    },
]
