// i18n copy keys and English defaults
// This structure is designed to be easily extended for multiple languages

export const copy = {
    // Common
    common: {
        loading: 'Loading...',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        create: 'Create',
        update: 'Update',
        close: 'Close',
        back: 'Back',
        next: 'Next',
        previous: 'Previous',
        search: 'Search...',
        noResults: 'No results found',
        tryAgain: 'Try Again',
        confirmDelete: 'Are you sure? This action cannot be undone.',
        permissionDenied: 'You do not have permission to perform this action.',
        sessionExpired: 'Your session has expired. Please log in again.',
    },

    // Auth
    auth: {
        login: 'Login',
        register: 'Register',
        logout: 'Logout',
        email: 'Email',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        firstName: 'First Name',
        lastName: 'Last Name',
        phone: 'Phone Number',
        accountType: 'Account Type',
        signIn: 'Sign In',
        signUp: 'Sign Up',
        forgotPassword: 'Forgot Password?',
        rememberMe: 'Remember me',
        createAccount: 'Create an account',
        haveAccount: 'Already have an account? Sign in',
        noAccount: "Don't have an account? Sign up",
        loginError: 'Invalid email or password',
        registerError: 'Failed to create account',
        registerSuccess: 'Account created successfully. Please log in.',
        emailAlreadyExists: 'Email already registered',
        phoneAlreadyExists: 'Phone number already registered',
    },

    // Members
    members: {
        title: 'Members',
        addMember: 'Add Member',
        editMember: 'Edit Member',
        deleteMember: 'Delete Member',
        memberDetail: 'Member Details',
        trainer: 'Trainer',
        joinDate: 'Join Date',
        status: 'Status',
        attendanceRate: 'Attendance Rate',
        actions: 'Actions',
        noMembers: 'No members found',
        addMemberSuccess: 'Member added successfully',
        updateMemberSuccess: 'Member updated successfully',
        deleteMemberSuccess: 'Member deleted successfully',
        deleteConfirm: 'Are you sure you want to delete this member?',
    },

    // Trainers
    trainers: {
        title: 'Trainers',
        addTrainer: 'Add Trainer',
        editTrainer: 'Edit Trainer',
        deleteTrainer: 'Delete Trainer',
        trainerDetail: 'Trainer Details',
        assignMembers: 'Assign Members',
        members: 'Members',
        noTrainers: 'No trainers found',
        addTrainerSuccess: 'Trainer added successfully',
        updateTrainerSuccess: 'Trainer updated successfully',
        deleteTrainerSuccess: 'Trainer deleted successfully',
    },

    // Users (Staff Management)
    users: {
        title: 'Staff Management',
        addUser: 'Add Staff',
        editUser: 'Edit Staff',
        deleteUser: 'Delete Staff',
        userDetail: 'Staff Details',
        role: 'Role',
        noUsers: 'No staff found',
        addUserSuccess: 'Staff member added successfully',
        updateUserSuccess: 'Staff member updated successfully',
        deleteUserSuccess: 'Staff member deleted successfully',
        roles: {
            ADMIN: 'Admin',
            STAFF: 'Staff',
            HR: 'HR',
        },
    },

    // Attendance
    attendance: {
        title: 'Attendance',
        checkIn: 'Check In',
        checkOut: 'Check Out',
        checkInSuccess: 'Checked in successfully',
        checkOutSuccess: 'Checked out successfully',
        alreadyCheckedIn: 'Already checked in',
        notCheckedIn: 'Not checked in',
        history: 'History',
        corrections: 'Corrections',
        recordCorrection: 'Record Correction',
        correctionSuccess: 'Correction recorded successfully',
        noAttendance: 'No attendance records found',
        memberselector: 'Select a member',
        checkingIn: 'Checking in...',
        checkingOut: 'Checking out...',
    },

    // Equipment
    equipment: {
        title: 'Equipment',
        addEquipment: 'Add Equipment',
        editEquipment: 'Edit Equipment',
        deleteEquipment: 'Delete Equipment',
        equipmentDetail: 'Equipment Details',
        name: 'Equipment Name',
        description: 'Description',
        quantity: 'Quantity',
        condition: 'Condition',
        conditions: {
            GOOD: 'Good',
            FAIR: 'Fair',
            POOR: 'Poor',
        },
        managedBy: 'Managed By',
        noEquipment: 'No equipment found',
        addEquipmentSuccess: 'Equipment added successfully',
        updateEquipmentSuccess: 'Equipment updated successfully',
        deleteEquipmentSuccess: 'Equipment deleted successfully',
    },

    // Inventory Movements
    inventory: {
        title: 'Inventory Movements',
        recordIncoming: 'Record Incoming',
        recordOutgoing: 'Record Outgoing',
        recordAdjustment: 'Record Adjustment',
        movementHistory: 'Movement History',
        type: 'Type',
        equipment: 'Equipment',
        quantity: 'Quantity',
        reason: 'Reason',
        note: 'Note',
        recordedAt: 'Recorded At',
        noMovements: 'No movements found',
        recordSuccess: 'Movement recorded successfully',
        types: {
            INCOMING: 'Incoming',
            OUTGOING: 'Outgoing',
            ADJUSTMENT: 'Adjustment',
        },
        reasons: {
            restock: 'Restock',
            sessionUse: 'Session Use',
            damage: 'Damage',
            loss: 'Loss',
            physicalCount: 'Physical Count',
            errorCorrection: 'Error Correction',
        },
    },

    // Errors
    errors: {
        required: 'This field is required',
        invalidEmail: 'Please enter a valid email address',
        invalidPhone: 'Please enter a valid phone number',
        passwordMismatch: 'Passwords do not match',
        passwordTooShort: 'Password must be at least 8 characters',
        invalidRole: 'Invalid role selected',
        duplicateEmail: 'Email already registered',
        duplicatePhone: 'Phone number already registered',
        notFound: 'Resource not found',
        unauthorized: 'Unauthorized access',
        serverError: 'Server error. Please try again later.',
        networkError: 'Network error. Please check your connection.',
    },
}
