import type { Message } from '@/types'

export const conversations: Message[] = [
    {
        id: 'msg001',
        senderId: 'm001',
        senderName: 'Mia Torres',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia',
        preview: 'Can I reschedule my PT session to Friday?',
        timestamp: '10:32 AM',
        unread: true,
        thread: [
            { id: 't001', senderId: 'm001', senderName: 'Mia Torres', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia', content: 'Hi coach, can I reschedule my PT session to Friday?', timestamp: '10:25 AM', isMe: false },
            { id: 't002', senderId: 'admin', senderName: 'You', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin', content: 'Sure Mia, what time works best for you?', timestamp: '10:27 AM', isMe: true },
            { id: 't003', senderId: 'm001', senderName: 'Mia Torres', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia', content: 'Around 5 PM would be great.', timestamp: '10:32 AM', isMe: false },
        ],
    },
    {
        id: 'msg002',
        senderId: 'm003',
        senderName: 'Priya Sharma',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
        preview: 'Thanks for the nutrition plan update.',
        timestamp: '09:45 AM',
        unread: false,
        thread: [
            { id: 't004', senderId: 'admin', senderName: 'You', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin', content: 'I uploaded your updated nutrition plan.', timestamp: '09:30 AM', isMe: true },
            { id: 't005', senderId: 'm003', senderName: 'Priya Sharma', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya', content: 'Thanks for the nutrition plan update.', timestamp: '09:45 AM', isMe: false },
        ],
    },
    {
        id: 'msg003',
        senderId: 'm006',
        senderName: 'Ethan Brooks',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan',
        preview: 'I need to freeze membership for 2 weeks.',
        timestamp: 'Yesterday',
        unread: true,
        thread: [
            { id: 't006', senderId: 'm006', senderName: 'Ethan Brooks', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan', content: 'I need to freeze my membership for 2 weeks due to travel.', timestamp: 'Yesterday', isMe: false },
        ],
    },
    {
        id: 'msg004',
        senderId: 'm009',
        senderName: 'Lena Mueller',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lena',
        preview: 'The spin class was amazing!',
        timestamp: 'Yesterday',
        unread: false,
        thread: [
            { id: 't007', senderId: 'm009', senderName: 'Lena Mueller', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lena', content: 'The spin class was amazing. Thank you!', timestamp: 'Yesterday', isMe: false },
        ],
    },
    {
        id: 'msg005',
        senderId: 'm011',
        senderName: 'Yuki Tanaka',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yuki',
        preview: 'Could you share tomorrow\'s class schedule?',
        timestamp: 'Mon',
        unread: false,
        thread: [
            { id: 't008', senderId: 'm011', senderName: 'Yuki Tanaka', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yuki', content: 'Could you share tomorrow\'s class schedule?', timestamp: 'Mon', isMe: false },
            { id: 't009', senderId: 'admin', senderName: 'You', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin', content: 'Sent to your email. Let me know if you need changes.', timestamp: 'Mon', isMe: true },
        ],
    },
    {
        id: 'msg006',
        senderId: 'm015',
        senderName: 'Emma Wilson',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
        preview: 'Can I add my friend for a trial pass?',
        timestamp: 'Sun',
        unread: true,
        thread: [
            { id: 't010', senderId: 'm015', senderName: 'Emma Wilson', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma', content: 'Can I add my friend for a trial pass this week?', timestamp: 'Sun', isMe: false },
        ],
    },
    {
        id: 'msg007',
        senderId: 'm017',
        senderName: 'Fatima Al-Rashid',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
        preview: 'Payment completed. Please confirm.',
        timestamp: 'Sat',
        unread: false,
        thread: [
            { id: 't011', senderId: 'm017', senderName: 'Fatima Al-Rashid', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima', content: 'Payment completed. Please confirm.', timestamp: 'Sat', isMe: false },
            { id: 't012', senderId: 'admin', senderName: 'You', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin', content: 'Confirmed. Thank you!', timestamp: 'Sat', isMe: true },
        ],
    },
    {
        id: 'msg008',
        senderId: 'm020',
        senderName: 'James Okafor',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
        preview: 'My app login is not working.',
        timestamp: 'Fri',
        unread: true,
        thread: [
            { id: 't013', senderId: 'm020', senderName: 'James Okafor', senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', content: 'My app login is not working after password reset.', timestamp: 'Fri', isMe: false },
        ],
    },
]
